name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Check version
        run: |
          if [ "$(git diff HEAD^ HEAD -- package.json | grep '\"version\"')" == "" ]; then
            echo "Version not updated in package.json"
            exit 1
          fi

      - name: Build package
        run: npm run build --if-present

      - name: Run tests
        run: npm run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set token npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
